"""initial_schema

Revision ID: 75291048e26c
Revises: 
Create Date: 2026-04-08 22:12:27.960233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75291048e26c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=False),
    sa.Column('material_code', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('original_body', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('collect_count', sa.Integer(), nullable=True),
    sa.Column('source_platform', sa.Text(), nullable=True),
    sa.Column('content_form', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('title_formula', sa.Text(), nullable=True),
    sa.Column('body_structure', sa.Text(), nullable=True),
    sa.Column('emotion_triggers', sa.Text(), nullable=True),
    sa.Column('selling_style', sa.Text(), nullable=True),
    sa.Column('composition_style', sa.Text(), nullable=True),
    sa.Column('color_tone', sa.Text(), nullable=True),
    sa.Column('scene_props', sa.Text(), nullable=True),
    sa.Column('tag_strategy', sa.Text(), nullable=True),
    sa.Column('analysis_status', sa.Text(), nullable=True),
    sa.Column('applied_to_engine', sa.Boolean(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_record_id'),
    sa.UniqueConstraint('material_code')
    )
    op.create_table('skus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=False),
    sa.Column('sku_code', sa.Text(), nullable=False),
    sa.Column('sku_name', sa.Text(), nullable=False),
    sa.Column('spu_code', sa.Text(), nullable=True),
    sa.Column('product_alias', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('material', sa.Text(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('style', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('selling_point_1', sa.Text(), nullable=True),
    sa.Column('selling_point_2', sa.Text(), nullable=True),
    sa.Column('selling_point_3', sa.Text(), nullable=True),
    sa.Column('price_range', sa.Float(), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('listing_status', sa.Text(), nullable=True),
    sa.Column('white_bg_urls', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_record_id'),
    sa.UniqueConstraint('sku_code')
    )
    op.create_table('sync_cursors',
    sa.Column('table_name', sa.Text(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_page_token', sa.Text(), nullable=True),
    sa.Column('sync_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=False),
    sa.Column('tag_code', sa.Text(), nullable=True),
    sa.Column('tag_name', sa.Text(), nullable=False),
    sa.Column('platforms', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('topic_heat', sa.Integer(), nullable=True),
    sa.Column('weight_score', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_record_id'),
    sa.UniqueConstraint('tag_code')
    )
    op.create_index('idx_tags_category_platform', 'tags', ['category', 'enabled'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_code', sa.Text(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_logs_created', 'task_logs', ['created_at'], unique=False)
    op.create_index('idx_task_logs_entity', 'task_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=True),
    sa.Column('plan_code', sa.Text(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('task_name', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=False),
    sa.Column('content_types', sa.Text(), nullable=True),
    sa.Column('target_platforms', sa.Text(), nullable=True),
    sa.Column('img_count', sa.Integer(), nullable=True),
    sa.Column('img_per_post', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('video_min_sec', sa.Integer(), nullable=True),
    sa.Column('video_max_sec', sa.Integer(), nullable=True),
    sa.Column('tag_inject_n', sa.Integer(), nullable=True),
    sa.Column('text_model', sa.Text(), nullable=True),
    sa.Column('image_model', sa.Text(), nullable=True),
    sa.Column('video_model', sa.Text(), nullable=True),
    sa.Column('exec_status', sa.Text(), nullable=True),
    sa.Column('confirmed_exec', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_record_id'),
    sa.UniqueConstraint('plan_code')
    )
    op.create_index('idx_plans_exec_status', 'plans', ['exec_status'], unique=False)
    op.create_table('contents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=True),
    sa.Column('content_code', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.Text(), nullable=True),
    sa.Column('target_platform', sa.Text(), nullable=True),
    sa.Column('content_type', sa.Text(), nullable=True),
    sa.Column('content_form', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('local_dir', sa.Text(), nullable=True),
    sa.Column('gen_status', sa.Text(), nullable=True),
    sa.Column('migrate_needed', sa.Boolean(), nullable=True),
    sa.Column('migrate_status', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_code'),
    sa.UniqueConstraint('feishu_record_id')
    )
    op.create_index('idx_contents_gen_status', 'contents', ['gen_status'], unique=False)
    op.create_index('idx_contents_plan_id', 'contents', ['plan_id'], unique=False)
    op.create_index('idx_contents_review_status', 'contents', ['review_status'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=True),
    sa.Column('prompt_code', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('prompt_type', sa.Text(), nullable=True),
    sa.Column('master_prompt', sa.Text(), nullable=True),
    sa.Column('sub_prompts', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_record_id'),
    sa.UniqueConstraint('prompt_code')
    )
    op.create_table('publish_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('feishu_record_id', sa.Text(), nullable=True),
    sa.Column('pub_code', sa.Text(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('publish_method', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('pub_status', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('post_url', sa.Text(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_record_id'),
    sa.UniqueConstraint('pub_code')
    )
    op.create_index('idx_publish_records_content_id', 'publish_records', ['content_id'], unique=False)
    op.create_index('idx_publish_records_pub_status', 'publish_records', ['pub_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_publish_records_pub_status', table_name='publish_records')
    op.drop_index('idx_publish_records_content_id', table_name='publish_records')
    op.drop_table('publish_records')
    op.drop_table('prompts')
    op.drop_index('idx_contents_review_status', table_name='contents')
    op.drop_index('idx_contents_plan_id', table_name='contents')
    op.drop_index('idx_contents_gen_status', table_name='contents')
    op.drop_table('contents')
    op.drop_index('idx_plans_exec_status', table_name='plans')
    op.drop_table('plans')
    op.drop_index('idx_task_logs_entity', table_name='task_logs')
    op.drop_index('idx_task_logs_created', table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index('idx_tags_category_platform', table_name='tags')
    op.drop_table('tags')
    op.drop_table('sync_cursors')
    op.drop_table('skus')
    op.drop_table('materials')
    # ### end Alembic commands ###
