import json, subprocess, os, time

BASE_TOKEN = "Ei9jbcsHianwvvsn5xScH8ANnnb"
TABLE_ID = "tbliWlwiyA4sppgY"
LARK_CLI = r"C:\Users\carson\AppData\Roaming\npm\lark-cli.cmd"

APPEARANCE = "年轻亚洲女性，时尚性感，身材好曲线自然，精致五官，表情自然真实，轻妆或自然妆，无过度美颜无过度修图"

scenes = [
    {
        "场景编号": "SC042",
        "场景名称": "首图·黄金时段街头侧逆光持机",
        "场景类型": "首图专用",
        "场景描述_中文": "傍晚黄金时段，年轻亚洲女性四分之三侧面站立于街头，逆光勾勒轮廓，手持挂链手机，链条在暖橙色光线下泛出金属光晕，背景城市光斑虚化",
        "场景基底_英文": "young Asian woman 3/4 angle on city street during golden hour, backlit warm orange glow, holding phone with decorative chain, chain catching golden light, blurred city bokeh background, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "黄金时段,暖调氛围,轮廓光感",
        "排除描述": "不要正午强光，不要链条反光过爆，不要背景过于空旷，不要人物表情呆滞",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 10,
        "景别": "中景/半身",
        "光源类型": "黄金时段自然光（逆光）",
        "拍摄角度": "平视/略仰",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "四分之三侧站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：黄金时段逆光+链条金属光晕，视觉冲击力强，适合得物首图"
    },
    {
        "场景编号": "SC043",
        "场景名称": "首图·咖啡厅坐姿链条自然垂落",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性坐于咖啡厅窗边，单手持挂链手机轻靠桌沿，链条自然垂落桌面，奶油暖色调窗边光，传递精致日常生活感",
        "场景基底_英文": "young Asian woman sitting at cafe window seat, one hand holding phone with chain draping naturally onto table, warm cream window light, cozy lifestyle atmosphere, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "奶油感,精致日常,窗边光影",
        "排除描述": "不要背景杂乱，不要链条被桌面遮挡，不要表情过于严肃，不要荧光灯硬光",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "自然光（窗边）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "坐姿侧对镜头",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：咖啡厅日常场景+链条自然垂落，生活质感强，受众广"
    },
    {
        "场景编号": "SC044",
        "场景名称": "首图·行走动态链条摇曳",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在城市街道或商场走廊中行走，手持挂链手机，链条随步伐自然摇曳，捕捉行进动态瞬间，背景虚化呈现速度感",
        "场景基底_英文": "young Asian woman walking on city street or mall corridor, holding phone with swaying chain, chain in natural motion, blurred background showing movement, candid dynamic feel, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "动感活力,自然抓拍,城市节奏",
        "排除描述": "不要链条模糊到看不清，不要动作夸张失真，不要背景过于单调，不要摆拍感",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "行走动态",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：行走中链条摇曳动态感，区别于静态摆拍，抓眼球效果佳"
    },
    {
        "场景编号": "SC045",
        "场景名称": "首图·公园草地阳光清新站姿",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站立于公园绿草地或树荫下，面向或略侧向镜头，手持挂链手机，阳光透过树叶形成光斑，背景绿意清新虚化",
        "场景基底_英文": "young Asian woman standing in park with green lawn or dappled tree shade, facing camera holding phone with chain, natural sunlight filtering through leaves creating bokeh, fresh and bright atmosphere, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "清新自然,阳光感,户外生机",
        "排除描述": "不要背景过于空旷，不要强烈正午直射光，不要链条被手臂遮挡，不要过度鲜艳滤镜",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "自然散射光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "自然站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：户外公园清新场景，链条与自然光配合，亲和力强"
    },
    {
        "场景编号": "SC046",
        "场景名称": "首图·极简白色背景正面亮相",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性正面站立于纯白或浅灰极简背景前，手持挂链手机，链条垂坠清晰，整体突出人物与链条，视觉干净有冲击力",
        "场景基底_英文": "young Asian woman standing face-on against pure white or light grey minimal background, holding phone with chain clearly visible and draping, clean commercial look with strong visual focus on person and chain, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "极简干净,商业感,视觉聚焦",
        "排除描述": "不要背景有杂物，不要打光产生过重阴影，不要人物服装与背景撞色，不要链条被手遮挡",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "柔光/补光灯",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "面向镜头站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：极简商业风，链条与人物一目了然，得物转化率高"
    },
    {
        "场景编号": "SC047",
        "场景名称": "首图·夜景霓虹灯光持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站立于夜晚城市霓虹灯或彩色路灯前，手持挂链手机，链条在彩色灯光下反射出绚丽金属色，背景城市夜景虚化，风格时髦前卫",
        "场景基底_英文": "young Asian woman at night in front of neon city lights, holding phone with chain reflecting colorful neon glow, chain catching vibrant metallic shimmer, blurred night city background, trendy and edgy atmosphere, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "夜间时髦,霓虹色感,前卫都市",
        "排除描述": "不要曝光过度链条失真，不要背景灯光喧宾夺主，不要表情过于强硬，不要纯黑暗看不清人物",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "霓虹灯/城市夜景光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "自然站立/略侧身",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：夜间霓虹场景差异化，链条反光效果独特，适合时髦前卫风格内容"
    },
    {
        "场景编号": "SC048",
        "场景名称": "首图·窗边室内侧光含蓄持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性靠近室内窗边，侧身或四分之三角度，手持挂链手机，窗边自然侧光勾勒轮廓，链条在侧光下呈现金属肌理，氛围安静高级",
        "场景基底_英文": "young Asian woman near indoor window, 3/4 angle, holding phone with chain, natural side window light sculpting her profile, chain showing metallic texture in sidelight, quiet sophisticated indoor mood, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "高级安静,侧光肌理,室内质感",
        "排除描述": "不要光线过暗，不要背景过于凌乱，不要人物表情不自然，不要链条完全没有光影变化",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "自然侧光（室内窗边）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "四分之三侧面",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：室内窗边侧光，链条金属肌理清晰，高级感突出"
    },
    {
        "场景编号": "SC049",
        "场景名称": "首图·穿搭全身链条整体亮相",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性全身穿搭出镜，手持挂链手机或让链条自然挂于身侧，整体造型完整，链条作为配饰点睛，背景干净或城市虚化",
        "场景基底_英文": "young Asian woman full body outfit shot, holding phone with chain or chain hanging naturally at side, complete styled look with chain as key accessory, clean or city bokeh background, fashion editorial feel, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "穿搭整体感,配饰点睛,时装编辑",
        "排除描述": "不要链条不可见，不要全身比例失调，不要背景抢眼，不要服装与链条风格严重不搭",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "全景/中景",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "全身站立展示",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：全身穿搭整体感，链条作为点睛配饰，带动穿搭种草转化"
    },
    {
        "场景编号": "SC050",
        "场景名称": "首图·台阶坐姿自然感持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性随意坐于室外台阶或石凳上，单腿微抬或自然放松姿势，手持挂链手机，链条垂落腿侧，整体传递放松真实的街头生活感",
        "场景基底_英文": "young Asian woman casually sitting on outdoor steps or stone bench, relaxed natural pose, holding phone with chain draping to side, authentic street lifestyle feel, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "随性真实,街头生活,放松感",
        "排除描述": "不要坐姿扭曲不自然，不要链条被大腿完全遮挡，不要背景过于脏乱，不要表情刻意",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景",
        "光源类型": "自然光",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "坐姿放松",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：坐姿放松真实感，区别于站立摆拍，亲近感强"
    },
    {
        "场景编号": "SC051",
        "场景名称": "首图·书店文艺场景持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在书店书架前驻足，手持挂链手机，链条自然垂落，暖色调书架背景虚化，整体传递文艺精致感与知性气质",
        "场景基底_英文": "young Asian woman standing by bookstore shelves, holding phone with decorative chain, chain hanging naturally, warm bokeh bookshelf background, literary and refined atmosphere, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "文艺知性,暖调书香,精致气质",
        "排除描述": "不要书架过于凌乱，不要背景颜色与链条完全冲突，不要表情过于严肃，不要链条被遮挡",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内暖光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "站立侧身/回头",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：书店文艺场景差异化，链条+知性气质，覆盖文艺向用户群"
    },
    {
        "场景编号": "SC052",
        "场景名称": "首图·花卉场景链条柔美亮相",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站于花店或户外花丛前，手持挂链手机，链条与花卉色彩呼应，背景花卉虚化柔美，整体传递少女感与精致生活态度",
        "场景基底_英文": "young Asian woman standing in front of flower shop or flower field, holding phone with chain, chain color complementing floral tones, soft blurred floral background, feminine and elegant lifestyle, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "花卉柔美,少女精致,色彩呼应",
        "排除描述": "不要花卉完全遮挡人物，不要色彩搭配混乱，不要链条被花束遮挡，不要背景过于复杂",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "自然散射光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "自然站立/微侧",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：花卉场景柔美风，链条与花色呼应，少女感强，节日前后效果佳"
    },
    {
        "场景编号": "SC053",
        "场景名称": "首图·商场扶梯俯视链条亮相",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站立或倚靠商场扶梯/栏杆，手持挂链手机朝向镜头，链条垂坠清晰，商场内部背景虚化呈现时尚感，角度略俯拍显高挑比例",
        "场景基底_英文": "young Asian woman standing or leaning on escalator or railing in shopping mall, holding phone with chain toward camera, chain clearly draping, blurred mall interior background, slightly top-down angle showing slim proportions, trendy urban feel, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "都市时髦,商场质感,比例显高",
        "排除描述": "不要背景人流过于杂乱，不要链条方向背离镜头，不要角度变形失真，不要人物表情无神",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内灯光",
        "拍摄角度": "略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "倚靠/持机朝向镜头",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：商场场景都市感，略俯角度显比例，链条自然垂坠"
    },
    {
        "场景编号": "SC054",
        "场景名称": "首图·雨天撑伞单手持机链条摇曳",
        "场景类型": "首图专用",
        "场景描述_中文": "阴雨天气，年轻亚洲女性一手撑伞一手持挂链手机，链条在雨天湿润空气中自然垂落，背景雨水模糊城市虚化，文艺氛围感强",
        "场景基底_英文": "young Asian woman holding umbrella in rainy weather, other hand holding phone with decorative chain hanging naturally, blurred rainy city background, moody artistic atmosphere with rain bokeh, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "雨天文艺,朦胧氛围,情绪感",
        "排除描述": "不要雨水完全遮挡链条，不要人物过于狼狈，不要背景完全漆黑，不要伞遮住人物面部",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "阴天自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "持伞站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：雨天场景情绪感强，差异化明显，文艺向用户高共鸣"
    },
    {
        "场景编号": "SC055",
        "场景名称": "首图·地铁/站台通勤持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站立于地铁站台或列车车厢内，手持挂链手机，链条自然垂落，地铁背景虚化，传递日常通勤时髦感",
        "场景基底_英文": "young Asian woman standing on subway platform or inside metro car, holding phone with chain, chain hanging naturally, blurred subway background, stylish daily commute feel, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "通勤时髦,城市日常,地铁感",
        "排除描述": "不要背景过于拥挤杂乱，不要链条被背包遮挡，不要荧光灯使肤色发黄，不要表情疲惫",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内灯光（地铁）",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "站立持机",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：通勤地铁场景，日常代入感强，目标用户共鸣高"
    },
    {
        "场景编号": "SC056",
        "场景名称": "首图·侧脸轮廓光持机展示",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性完整侧脸朝向一侧，手持挂链手机置于胸前，链条垂落，轮廓光勾勒侧脸线条，背景简洁，突出侧颜美感与链条垂坠形态",
        "场景基底_英文": "young Asian woman in full side profile, holding phone with chain in front of chest, chain draping down, rim light highlighting facial profile, clean simple background, elegant side profile aesthetic with chain, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "侧颜美感,轮廓光感,高冷气质",
        "排除描述": "不要侧脸角度看不见链条，不要背景太复杂，不要轮廓光过曝，不要人物表情过于绷紧",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "侧逆光/轮廓光",
        "拍摄角度": "正侧面",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "侧脸朝向一侧",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：侧颜美感+链条垂坠，高级感强，视觉记忆点突出"
    },
    {
        "场景编号": "SC057",
        "场景名称": "首图·跳跃欢快动态链条飞扬",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在户外做轻微跳跃或踮脚欢快动作，手持挂链手机，链条随跳跃动作飞扬飘动，背景明亮开阔，传递青春活力",
        "场景基底_英文": "young Asian woman doing a light jump or tiptoe motion outdoors, holding phone with chain flying through the air, chain in energetic motion mid-jump, bright open background, youthful and cheerful energy, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "青春活力,欢快动感,链条飞扬",
        "排除描述": "不要动作僵硬，不要链条模糊完全看不清，不要背景过暗，不要跳跃高度过分夸张",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/全身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "跳跃/踮脚动态",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：跳跃动态链条飞扬，青春活力感，年轻用户情绪共鸣强"
    },
    {
        "场景编号": "SC058",
        "场景名称": "首图·双人闺蜜同框持机链条展示",
        "场景类型": "首图专用",
        "场景描述_中文": "两位年轻亚洲女性并肩站立或相互靠近，各自手持挂链手机，链条清晰可见，两人搭配感强，背景城市或简洁虚化，传递闺蜜同款的社交属性",
        "场景基底_英文": "two young Asian women standing together or leaning close, each holding phone with decorative chain, chains clearly visible on both, matching energy and style, city or simple bokeh background, friendship sharing same-style accessory vibe, young Asian women, slim proportions, natural makeup, 20s",
        "风格基调词": "闺蜜同款,社交属性,双人时髦",
        "排除描述": "不要两人链条互相遮挡，不要双人构图不平衡，不要背景太杂乱，不要表情不自然",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜（双人）",
        "外貌风格": APPEARANCE,
        "姿态倾向": "并肩站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：闺蜜同款场景，社交传播属性强，带动买家秀UGC"
    },
    {
        "场景编号": "SC059",
        "场景名称": "首图·冬日保暖穿搭持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿着冬日厚外套或毛衣搭配，手持挂链手机，链条在深色冬装上形成视觉对比，背景户外冬日氛围或室内暖调，传递冬季时髦感",
        "场景基底_英文": "young Asian woman wearing cozy winter coat or sweater outfit, holding phone with chain, chain creating visual contrast against winter clothes, outdoor winter or warm indoor background, stylish cold-weather look with chain as accessory highlight, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "冬日保暖,厚实质感,冷暖对比",
        "排除描述": "不要链条与深色服装完全融为一体看不清，不要背景太冷太暗，不要过厚衣物使比例不好，不要表情冷淡无神",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "自然站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：冬季穿搭场景，季节感强，链条与厚实外套形成视觉反差"
    },
    {
        "场景编号": "SC060",
        "场景名称": "首图·镜前自拍角度模拟持机",
        "场景类型": "首图专用",
        "场景描述_中文": "模拟用户自拍视角，年轻亚洲女性面对镜头高举手机，链条自然从手间垂下，画面中清晰可见手机+链条+人物上半身，传递日常自拍的亲近感",
        "场景基底_英文": "young Asian woman holding phone up in selfie pose toward camera, chain hanging down naturally from hand, phone and chain clearly visible with person's upper body in frame, intimate daily selfie vibe, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "自拍亲近感,日常视角,真实互动",
        "排除描述": "不要手臂遮挡链条主体，不要角度过于仰拍变形，不要光线过暗，不要表情夸张失真",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "近景/半身",
        "光源类型": "自然光/柔光",
        "拍摄角度": "略仰（模拟自拍角度）",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "举手机自拍姿势",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：模拟自拍视角，亲近感强，用户代入感高，链条垂坠自然可见"
    },
    {
        "场景编号": "SC061",
        "场景名称": "首图·艺术涂鸦墙背景持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站于街头彩色涂鸦墙前，手持挂链手机，链条金属色与鲜艳涂鸦背景形成时髦对比，整体传递个性街头艺术感",
        "场景基底_英文": "young Asian woman standing in front of colorful street art graffiti wall, holding phone with metallic chain, chain contrasting with vibrant mural colors, edgy street art personality, young Asian woman, slim proportions, natural makeup, 20s",
        "风格基调词": "街头艺术,个性对比,涂鸦时髦",
        "排除描述": "不要背景涂鸦太混乱导致链条迷失，不要人物与背景颜色完全融合，不要构图主次不分，不要表情过于严肃",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "自然靠墙/站立",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：涂鸦墙背景差异化场景，个性街头感，链条金属感与彩色背景形成强对比"
    },
]

for s in scenes:
    tmp_path = f"tmp/_sc_hero_{s['场景编号']}.json"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(s, f, ensure_ascii=False)

    result = subprocess.run(
        [LARK_CLI, "base", "+record-upsert",
         "--base-token", BASE_TOKEN,
         "--table-id", TABLE_ID,
         "--json", f"@{tmp_path}"],
        capture_output=True, encoding="utf-8", cwd="D:/AI-Content-Hub"
    )
    os.remove(tmp_path)
    code = s["场景编号"]
    if result.returncode == 0:
        print(f"OK {code} {s['场景名称']}")
    else:
        print(f"FAIL {code} {s['场景名称']}")
        print("  stderr:", result.stderr[:300])
    time.sleep(0.5)

print("Done.")
