import json, subprocess, os, time

BASE_TOKEN = "Ei9jbcsHianwvvsn5xScH8ANnnb"
TABLE_ID = "tbliWlwiyA4sppgY"
LARK_CLI = r"C:\Users\carson\AppData\Roaming\npm\lark-cli.cmd"

APPEARANCE = "年轻亚洲女性，时尚性感，身材好曲线自然，精致五官，表情自然真实，轻妆或自然妆，无过度美颜无过度修图"

scenes = [
    {
        "场景编号": "SC072",
        "场景名称": "首图·健身房镜前持机自拍",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在健身房落地镜前，健身装束，单手持挂链手机朝向镜面自拍，链条在镜中清晰可见，背景健身器械虚化，传递活力时髦感",
        "场景基底_英文": "young Asian woman in gym workout outfit standing in front of full-length mirror, holding phone with chain in mirror selfie pose, chain clearly visible in reflection, gym equipment blurred background, sporty chic energy, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "健身活力,镜前自拍,运动时髦",
        "排除描述": "不要健身器械完全遮挡人物，不要镜面反射混乱，不要链条在镜中看不清，不要背景过于嘈杂",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "室内灯光（健身房）",
        "拍摄角度": "平视/略仰（镜面自拍视角）",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "镜前自拍/单手持机",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：健身房镜前自拍，链条镜像双重出现，运动时髦感强，覆盖健身爱好者"
    },
    {
        "场景编号": "SC073",
        "场景名称": "首图·健身房哑铃区休息持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在健身房哑铃区训练间隙坐于长凳上，手持挂链手机，链条自然垂落，运动装束显现身材线条，背景哑铃架虚化，传递精致运动生活感",
        "场景基底_英文": "young Asian woman sitting on gym bench during workout rest, holding phone with chain naturally draping, athletic outfit showing body curves, blurred dumbbell rack background, refined active lifestyle, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "运动休息,精致健身,力量感",
        "排除描述": "不要表情过于疲惫，不要背景健身器械过于杂乱，不要链条被运动手套遮挡，不要姿势不自然",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内灯光（健身房）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "坐于长凳休息",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：健身间隙场景，精致运动生活感，链条与运动装束形成时髦搭配"
    },
    {
        "场景编号": "SC074",
        "场景名称": "首图·瑜伽垫旁瑜伽裤持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿着瑜伽裤坐或站于瑜伽垫旁，手持挂链手机，链条与光滑瑜伽裤形成材质对比，背景瑜伽馆或室内虚化，传递精致健康生活感",
        "场景基底_英文": "young Asian woman in yoga pants sitting or standing near yoga mat, holding phone with chain, metallic chain contrasting with smooth yoga pants fabric, blurred yoga studio or indoor background, mindful healthy lifestyle, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "瑜伽精致,健康生活,材质对比",
        "排除描述": "不要瑜伽垫遮挡链条，不要姿势夸张，不要背景过于混乱，不要链条与瑜伽裤颜色完全融合",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景",
        "光源类型": "自然光/室内柔光",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "瑜伽坐姿/站姿",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：瑜伽裤场景，精致健康风，链条金属感与运动感碰撞，覆盖瑜伽健身用户"
    },
    {
        "场景编号": "SC075",
        "场景名称": "首图·瑜伽裤户外伸展动作持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿瑜伽裤在公园或户外做伸展动作，手持或腕挂链条手机，链条随动作呈现动感形态，背景绿意自然虚化，传递活力自由感",
        "场景基底_英文": "young Asian woman in yoga pants doing stretch pose outdoors in park, holding or wrist-wearing phone with chain in dynamic position, chain in natural motion, blurred green nature background, free active energy, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "户外活力,瑜伽动感,自由伸展",
        "排除描述": "不要伸展动作过于极端，不要链条在动作中完全看不见，不要背景与人物融合，不要穿着风格不符",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/全身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "伸展动作/户外瑜伽",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：户外瑜伽伸展场景，动感自然，链条随动作呈现活力，差异化显著"
    },
    {
        "场景编号": "SC076",
        "场景名称": "首图·迷你裙街头行走持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿迷你裙在时尚街头行走，手持挂链手机，链条随步伐摇曳，短裙与链条共同传递时髦女孩感，背景城市街头虚化",
        "场景基底_英文": "young Asian woman in mini skirt walking on fashionable street, holding phone with swaying chain, chain and mini skirt creating trendy girl aesthetic, blurred urban street background, chic street style energy, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "迷你裙时髦,街头女孩,动感活力",
        "排除描述": "不要短裙遮挡链条，不要行走动作不自然，不要背景过于嘈杂，不要穿搭风格违和",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "自然光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "行走/自然步伐",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：迷你裙+街头行走，时髦感强，链条与短裙共同塑造潮流女孩形象"
    },
    {
        "场景编号": "SC077",
        "场景名称": "首图·迷你裙咖啡厅坐姿持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿迷你裙坐于咖啡厅，双腿交叉优雅，手持挂链手机轻搭桌沿，链条垂落，暖色调咖啡厅背景虚化，传递精致时髦的都市女孩感",
        "场景基底_英文": "young Asian woman in mini skirt sitting elegantly cross-legged at cafe, holding phone with chain draping on table edge, warm cafe bokeh background, sophisticated urban girl aesthetic, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "精致优雅,咖啡约会,都市女孩",
        "排除描述": "不要坐姿不雅观，不要链条被咖啡杯遮挡，不要背景过于杂乱，不要短裙坐姿走光",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/半身",
        "光源类型": "自然光（窗边）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "优雅坐姿/双腿交叉",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：迷你裙咖啡厅，精致都市感，链条垂坠与优雅坐姿呼应，转化率高"
    },
    {
        "场景编号": "SC078",
        "场景名称": "首图·迷你裙户外台阶坐姿",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿迷你裙在户外石台阶上自然坐立，手持挂链手机，链条垂落腿侧，阳光照射，背景城市或建筑虚化，整体时髦随性",
        "场景基底_英文": "young Asian woman in mini skirt sitting naturally on outdoor stone steps, holding phone with chain draping beside leg, sunlight, blurred urban or architectural background, effortlessly chic street style, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "随性时髦,阳光户外,街头真实",
        "排除描述": "不要坐姿不舒适，不要短裙坐姿失态，不要链条被腿完全压住，不要背景过于脏乱",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景",
        "光源类型": "自然光（阳光）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "台阶坐姿放松",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：迷你裙台阶场景，随性真实，链条自然呈现，阳光户外氛围感强"
    },
    {
        "场景编号": "SC079",
        "场景名称": "首图·户外跑步后手持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性跑步结束后站于户外道路或公园，轻微喘息自然状态，手持挂链手机，链条随着胸口起伏自然摆动，运动装束，背景绿色户外虚化",
        "场景基底_英文": "young Asian woman after outdoor run on road or park path, natural breathing post-workout, holding phone with chain in gentle motion, athletic outfit, blurred green outdoor background, authentic active lifestyle, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "运动后自然,跑步活力,户外清新",
        "排除描述": "不要表情过于疲惫难看，不要背景过于空旷，不要链条在运动中看不清，不要全程跑步动作（要跑后停止）",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "自然光（户外）",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "跑步后站立自然",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：跑步后场景，真实运动感，链条与运动装束结合，覆盖跑步爱好者群体"
    },
    {
        "场景编号": "SC080",
        "场景名称": "首图·跑步机上持机动态",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在跑步机上慢跑，单手持挂链手机，链条随跑步节奏自然晃动，健身房背景虚化，传递边运动边刷手机的现代生活感",
        "场景基底_英文": "young Asian woman jogging on treadmill, holding phone with chain swaying rhythmically with running motion, gym background blurred, modern multitasking active lifestyle, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "跑步机动感,现代健身,链条摇曳",
        "排除描述": "不要跑步姿势变形，不要链条摇曳幅度过大失控，不要健身房背景过于抢眼，不要表情痛苦",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内灯光（健身房）",
        "拍摄角度": "平视/略侧",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "跑步机慢跑动态",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：跑步机动态场景，链条随运动晃动，现代生活感强，与健身受众高共鸣"
    },
    {
        "场景编号": "SC081",
        "场景名称": "首图·小轿车内驾驶座持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性坐于小轿车驾驶座，手持挂链手机，链条自然垂落于中控台附近，车窗外城市背景虚化，传递都市通勤出行感",
        "场景基底_英文": "young Asian woman in car driver seat holding phone with chain hanging naturally near center console, blurred city scenery through window, urban commute daily life feel, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "车内通勤,都市日常,出行感",
        "排除描述": "不要车内显得凌乱，不要链条与方向盘混在一起，不要背景车外过亮曝光，不要驾驶姿势有安全隐患",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/近景",
        "光源类型": "自然光（车窗透光）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "驾驶座坐姿持机",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：车内场景代入感强，链条垂落中控，都市女孩出行感，受众广覆盖有车用户"
    },
    {
        "场景编号": "SC082",
        "场景名称": "首图·小轿车副驾座窗边自拍",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性坐于小轿车副驾座，侧靠窗边，手持挂链手机朝向自己拍摄，链条在车内侧逆光下形成金属光泽，车窗外风景虚化，传递旅途时髦感",
        "场景基底_英文": "young Asian woman sitting in car passenger seat leaning toward window, holding phone with chain in selfie position, chain catching metallic sheen from window side lighting, blurred scenery outside, road trip chic feeling, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "副驾自拍,旅途时髦,车窗光感",
        "排除描述": "不要车内光线过暗，不要链条被车门扶手遮挡，不要背景车外过曝，不要表情不自然",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "近景/半身",
        "光源类型": "自然光（车窗侧光）",
        "拍摄角度": "平视/略仰（自拍角度）",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "副驾座侧靠自拍",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：副驾自拍场景，旅途感强，链条车窗光泽效果好，高共鸣场景"
    },
    {
        "场景编号": "SC083",
        "场景名称": "首图·车内后座链条展示",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性坐于后排座位，单手持挂链手机在腿上，链条自然垂坠，车窗透光形成柔美侧光，背景车窗外城市或风景虚化，传递精致出行感",
        "场景基底_英文": "young Asian woman in back seat of car, holding phone with chain resting on lap naturally, soft side light from window, blurred city or landscape through car window, refined travel lifestyle, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "后座出行,柔美光感,精致旅途",
        "排除描述": "不要车内过于凌乱，不要链条被腿完全遮挡，不要车外背景太亮掩盖人物，不要座椅颜色与链条完全融合",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "自然光（车窗透光）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "后座放松坐姿",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：后排出行场景，链条与柔美车窗光结合，精致旅途感，场景差异化明显"
    },
    {
        "场景编号": "SC084",
        "场景名称": "首图·健身房出入口持机亮相",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性站于健身房门口或入口处，健身包挎肩，手持挂链手机，链条清晰呈现，背景健身房玻璃门或Logo虚化，传递精致健身女孩形象",
        "场景基底_英文": "young Asian woman at gym entrance with gym bag on shoulder, holding phone with chain clearly visible, blurred gym glass door or logo background, polished fitness girl aesthetic, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "健身女孩,入场感,精致运动",
        "排除描述": "不要健身包遮挡链条，不要背景健身房Logo过于突出，不要表情过于严肃，不要光线太暗",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内外混合光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "站立持机/挎包",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：健身房门口场景，出入场仪式感，精致健身女孩形象，链条作为运动潮流配件"
    },
    {
        "场景编号": "SC085",
        "场景名称": "首图·瑜伽裤镜前全身展示",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿瑜伽裤在落地镜前展示全身，手持挂链手机链条清晰可见，全身比例展示，背景简洁，传递身材管理与时髦生活方式",
        "场景基底_英文": "young Asian woman in yoga pants full body pose in front of floor mirror, holding phone with chain clearly visible, full proportions on display, clean background, body confidence and stylish healthy lifestyle, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "全身展示,瑜伽裤比例,健康自信",
        "排除描述": "不要镜面反射凌乱，不要链条在镜中看不清楚，不要背景过于复杂，不要全身比例变形",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "全景/中景",
        "光源类型": "室内柔光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "全身站立展示",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：瑜伽裤全身镜前，身材与链条共同出镜，视觉吸引力强，传播性高"
    },
    {
        "场景编号": "SC086",
        "场景名称": "首图·跑步道路侧面动态",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在城市跑道或公园小路侧面奔跑，手持挂链手机，链条随跑步动作飞扬，运动装束清晰，背景道路或绿植速度虚化，传递青春活力感",
        "场景基底_英文": "young Asian woman running from side angle on city track or park path, holding phone with chain flying in motion, athletic outfit visible, speed-blurred road or green background, youthful energetic vibe, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "跑步动感,侧面速度,青春活力",
        "排除描述": "不要跑步姿势变形丑陋，不要链条模糊到完全看不清，不要背景过于空旷，不要光线过暗",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/全身",
        "光源类型": "自然光",
        "拍摄角度": "侧面平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "奔跑侧面动态",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：跑步侧面动态，链条飞扬感强，速度感与青春活力突出，差异化明显"
    },
    {
        "场景编号": "SC087",
        "场景名称": "首图·迷你裙商场购物持机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿迷你裙在商场内购物，手持挂链手机，另一手提购物袋，链条清晰可见，商场背景灯光华丽虚化，传递时髦购物女孩感",
        "场景基底_英文": "young Asian woman in mini skirt shopping in mall, holding phone with chain, shopping bag in other hand, chain clearly visible, blurred glamorous mall lighting background, stylish shopping girl aesthetic, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "购物时髦,商场女孩,迷你裙潮流",
        "排除描述": "不要购物袋遮挡链条，不要商场背景过于嘈杂，不要表情过于严肃，不要服装与场景违和",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内商场灯光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "行走/购物自然姿态",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：迷你裙商场场景，购物女孩时髦感，链条与华丽商场背景呼应"
    },
    {
        "场景编号": "SC088",
        "场景名称": "首图·车内等待低头刷机链条垂落",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性坐于车内低头看手机，链条从手中自然垂落于腿上，侧逆光或车顶灯光勾勒链条金属质感，传递碎片化时间的精致感",
        "场景基底_英文": "young Asian woman in car looking down at phone, chain hanging naturally onto lap from hand, side rim light or interior car light highlighting chain metallic texture, intimate fragmented time aesthetic, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "碎片时间,低头看机,链条垂落",
        "排除描述": "不要低头角度过大看不见脸，不要车内环境太暗，不要链条完全被腿遮挡，不要背景车外过亮",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/近景",
        "光源类型": "自然光/车内灯光",
        "拍摄角度": "略俯/平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "低头看手机/自然坐姿",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：车内等待看机场景，真实日常代入感，链条垂落自然，精致碎片感"
    },
    {
        "场景编号": "SC089",
        "场景名称": "首图·健身后更衣室持机出镜",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性健身后在更衣室内换装，手持挂链手机，链条与干净整洁的更衣室背景形成时髦对比，传递健身完成后的满足感与精致感",
        "场景基底_英文": "young Asian woman post-workout in gym locker room, holding phone with chain, chain contrasting with clean locker room background, satisfied and polished post-gym energy, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "健身后满足,更衣室精致,运动完成感",
        "排除描述": "不要更衣室背景凌乱，不要链条被衣物遮挡，不要表情疲惫无神，不要背景隐私元素入镜",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "中景/半身",
        "光源类型": "室内灯光",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "站立持机",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：健身后更衣室，真实运动生活感，链条精致感与运动完成感结合"
    },
    {
        "场景编号": "SC090",
        "场景名称": "首图·迷你裙户外旋转动态",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性穿迷你裙在户外做轻微旋转动作，短裙扬起，手持挂链手机链条飞扬，背景户外阳光明亮虚化，整体传递青春自由的时髦感",
        "场景基底_英文": "young Asian woman in mini skirt doing a light spin outdoors, skirt lifting in motion, holding phone with chain flying outward, bright sunny outdoor background bokeh, youthful free-spirited chic, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "旋转动感,迷你裙飞扬,自由时髦",
        "排除描述": "不要旋转过于夸张失态，不要链条模糊到完全不可见，不要短裙旋转走光，不要背景过暗",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 9,
        "景别": "中景/全身",
        "光源类型": "自然光（阳光）",
        "拍摄角度": "平视",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "旋转动态/裙摆飞扬",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图高权重：迷你裙旋转动感，链条飞扬，裙摆与链条共同呈现动态美，视觉冲击力强"
    },
    {
        "场景编号": "SC091",
        "场景名称": "首图·车内挂链手机车载支架取机",
        "场景类型": "首图专用",
        "场景描述_中文": "年轻亚洲女性在车内从车载支架上取下挂链手机的动作瞬间，链条随取机动作自然摆动，车内环境整洁，车窗透入自然光，传递真实出行日常感",
        "场景基底_英文": "young Asian woman's hand reaching to take phone with chain from car mount holder, chain swinging naturally in action, clean car interior, natural light from window, authentic daily driving lifestyle moment, young Asian woman, fashionable sexy, natural curves, natural makeup, 20s",
        "风格基调词": "取机动作,车内日常,真实出行",
        "排除描述": "不要动作过于夸张，不要链条缠绕支架，不要车内环境凌乱，不要光线过暗",
        "适用品类": "手机链",
        "适用平台": "得物",
        "是否启用": True,
        "权重": 8,
        "景别": "近景/中景",
        "光源类型": "自然光（车窗）",
        "拍摄角度": "平视/略俯",
        "人物类型": "真人出镜",
        "外貌风格": APPEARANCE,
        "姿态倾向": "取机动作瞬间",
        "性别倾向": "女",
        "年龄段": "18-26岁",
        "备注": "首图：车内取机动作，真实日常场景，链条摆动自然，出行感强，差异化明显"
    },
]

for s in scenes:
    tmp_path = f"tmp/_sc_lifestyle_{s['场景编号']}.json"
    with open(tmp_path, "w", encoding="utf-8") as f:
        json.dump(s, f, ensure_ascii=False)

    result = subprocess.run(
        [LARK_CLI, "base", "+record-upsert",
         "--base-token", BASE_TOKEN,
         "--table-id", TABLE_ID,
         "--json", f"@{tmp_path}"],
        capture_output=True, encoding="utf-8", cwd="D:/AI-Content-Hub"
    )
    os.remove(tmp_path)
    code = s["场景编号"]
    if result.returncode == 0:
        print(f"OK {code} {s['场景名称']}")
    else:
        print(f"FAIL {code} {s['场景名称']}")
        print("  stderr:", result.stderr[:300])
    time.sleep(0.5)

print("Done.")
